stages:
- name: 运行脚本
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: mvn clean install
- name: 构建并发布镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: get_user-info:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.192.14.68:30002
timeout: 60
notification: {}
